### ISSUE TITLE
redirect /?login=done to profile page

### ISSUE THREAD

**Issue by danimesq** [mkg20001/ZeroMe#23]
The /?login=done page is empty. It isn't nice for the user is visiting for the first time to need to remove it from URL. Can you create a page with working top nav and a welcome message?

**Comment by mkg20001** [comment]
I never saw this page. When does it appear?

**Comment by danimesq** [comment]
When I use a proxy, after login with my privatekey.

**Comment by danimesq** [comment]
Updated the description of my latest comment.

**Comment by mkg20001** [comment]
> When I use a proxy, after login with my privatekey.

That seems to be a bug/feature in the MultiUser Plugin

**Comment by danimesq** [comment]
I think if you create a page with the same url, this can work.

**Comment by mkg20001** [comment]
So that it redirects page "login=done" to home?

**Comment by danimesq** [comment]
Yes. Or to profile. Or show a welcome message with the top bar.

**Comment by mkg20001** [comment]
Ok, but that should be fixed in ZeroNet itself too

**Comment by danimesq** [comment]
@HelloZeroNet.
