### ISSUE TITLE
"Edit Profile" is active if switch to user profile page but "Background Settings" won't show

### ISSUE THREAD

**Issue by jerry-wolf** [mkg20001/ZeroMe#61]
1. Enter user profile page.
2. Active "Edit Profile".
3. Switch to any other page.
4. Switch back user profile page.
5. Can't find "Background Settings".

**Comment by danimesq** [comment]
Also - as I see - when you edit your username and submit, the background settings disappears.

**Comment by danimesq** [comment]
@mkg20001

**Comment by mkg20001** [comment]
Related: mkg20001#72
data.json is fetched after everything, this causes all the problems.

**Comment by mkg20001** [comment]
Could you please check if the bug still occurs?

**Comment by danimesq** [comment]
For me, this seems to be fixed. And for you, @l5h5t7 ?

**Comment by jerry-wolf** [comment]
Yes, it's fixed.
