### ISSUE TITLE
[Github] Turn "Patch 1" and "Patch 1.1" into one

### ISSUE THREAD

**Issue by danimesq** [mkg20001/ZeroMe#76]

**Comment by mkg20001** [comment]
Why? The Patch 1 is for the current pr 1

**Comment by danimesq** [comment]
I think its time for Nofish review and merge it. I don't think we have more to do in the current pull request. But its just my opinion.

**Comment by mkg20001** [comment]
Bugfixes are still a todo

**Comment by danimesq** [comment]
In which part you're in now?

**Comment by mkg20001** [comment]
mkg20001#72
